# fly.toml app configuration file generated for fantea on 2024-01-15T10:30:00.000Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "fantea"
primary_region = "mad"  # Madrid, España - puedes cambiarlo según tu preferencia

[build]

[env]
  # Variables de entorno si necesitas

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = 15000
  grace_period = "10s"
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = 10000
  tls_skip_verify = false

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = 15000
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 10000
    tls_skip_verify = false
    headers = {}

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256 